---
title: "Data Project Team GoBills"
author: "STAT 420, Summer 2023, Naveen Baskaran (nc42), Frank Salamone (frankns2), Aleksandr Stpenko(as99)"
date: ''
output:
  html_document:
    theme: readable
    toc: yes
  word_document:
    toc: yes
  pdf_document: default
urlcolor: cyan
---


***

### 1. The names of the students who will be contributing to the group project.

Naveen Baskaran (nc42)
Frank Salamone (frankns2)
Aleksandr Stepenko (as99)

### 2. A tentative title for the project.

“Predicting Airbnb Prices in London on Weekends”

### 3. Description of the data file (what they contain including number of variables and number of records). You do not necessarily have to list all the variables, but at least mention those of greatest importance.

Our dataset concerns Airbnb rentals in London on the weekends.  It contains 19 variables in this dataset with 5379 records. These records consist of information regarding the characteristics of each rental, and the total price of the listing.  Our dataset is a subset of a larger collection of Airbnb listings in many European cities.

The most important variable is realSum, which is the total price of the listing, and will serve as our response.  There are many categorical variables, including, most importantly,  room_type, room_shared, and host_is_superhost.  The distance to city center, dist, and metro_dist, the distance to the nearest metro station, will be important continuous numeric variables.  

### 4. Background information on the data sets, including specific citation of their source (so that I can also access it).

This dataset was found on Kaggle. Briefly, it is a part of a larger set of Airbnb prices in European cities.  Please see the dataset description below (taken from Kaggle).

https://www.kaggle.com/datasets/thedevastator/airbnb-prices-in-european-cities?resource=download

“This dataset provides a comprehensive look at Airbnb prices in some of the most popular European cities. Each listing is evaluated for various attributes such as room types, cleanliness and satisfaction ratings, bedrooms, distance from the city center, and more to capture an in-depth understanding of Airbnb prices on both weekdays and weekends. Using spatial econometric methods, we analyze and identify the determinants of Airbnb prices across these cities. Our dataset includes information such as realSum (the total price of the listing), room_type (private/shared/entire home/apt), host_is_superhost (boolean value indicating if host is a superhost or not), multi (indicator whether listing is for multiple rooms or not), biz (business indicator) , guest_satisfaction_overall (overall rating from guests comparing all listings offered by host ), bedrooms, dist (distance from city center) , lng & lat coordinates for location identification etc. We hope that this data set offers insight into how global markets are affected by social dynamics and geographical factors which in turn determine pricing strategies for optimal profitability!”

### 5. A brief statement of the business, science, research, or personal interest you have in the data set which you hope to explore. 

From an outsider’s perspective, the Airbnb platform has revolutionized the renting of rooms much as Uber has revolutionized ridesharing.  Airbnb allows users of the platform to monetize property that they would not be able to otherwise.  In order to determine if renting out a room is a good business case or worth the owner’s time, it would be helpful to have an estimate of how much income the room would generate.  Our proposal is to develop a model, trained on the London Weekend Airbnb data, that could predict the room rental income based on predictors known to the person putting the room up for rent.  

### 6. Evidence that the data can be loaded into R. Load the data, and print the first few values of the response variable as evidence.

**Solution**

```{r}
london = read.csv("london_weekends.csv")
head(london$realSum)
head(london)
nrow(london)
ncol(london)
```


***

